# Hugo configuration
baseURL = "https://new.openboxes.com/"
languageCode = "en-us"
title = "OpenBoxes"
theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "openboxes"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-37396941-2"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-home'></i>"
    urk = "/"
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-info'></i>"
    weight = 2

[[menu.main]]
    name = "About OpenBoxes"
    parent = "about"
    pre = "<i class='fa fa-info'></i>"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Features"
    parent = "about"
    pre = "<i class='fa fa-list'></i>"
    url  = "/features/"
    weight = 2

[[menu.main]]
    name = "Pricing"
    parent = "about"
    pre = "<i class='fa fa-coffee'></i>"
    url  = "/pricing/"
    weight = 3

[[menu.main]]
    name = "Roadmap"
    parent = "about"
    pre = "<i class='fa fa-road'></i>"
    url  = "/roadmap/"
    weight = 4

[[menu.main]]
    name = "Users"
    parent = "about"
    pre = "<i class='fa fa-map'></i>"
    url  = "/users/"
    weight = 5

[[menu.main]]
    name = "Demo"
    pre = "<i class='fa fa-desktop'></i>"
    url  = "https://demo.openboxes.com"
    hrefTargetBlank = true
    weight =



[[menu.main]]
    identifier = "getting-started"
    name = "Get Started"
    pre = "<i class='fa fa-rocket'></i>"
    url  = "/getting-started/"
    weight = 4

[[menu.main]]
    name = "Downloads"
    parent = "getting-started"
    pre = "<i class='fa fa-download'></i>"
    url  = "/downloads/"
    weight = 1

[[menu.main]]
    name = "Source Code"
    parent = "getting-started"
    pre = "<i class='fa fa-code'></i>"
    url  = "https://github.com/openboxes/openboxes"
    weight = 2

[[menu.main]]
    name = "Installation"
    parent = "getting-started"
    pre = "<i class='fa fa-cloud'></i>"
    url  = "/installation/"
    weight = 3

[[menu.main]]
    name = "Tutorials"
    parent = "getting-started"
    pre = "<i class='fa fa-film'></i>"
    url  = "/tutorials/"
    weight = 4

[[menu.main]]
    identifier = "community"
    name = "Community"
    pre = "<i class='fa fa-users'></i>"
    url  = "/community/"
    weight = 5

[[menu.main]]
    identifier = "discuss"
    name = "Discuss"
    parent = "community"
    pre = "<i class='fa fa-comment'></i>"
    url  = "http://discuss.openboxes.com"
    weight = 1

[[menu.main]]
    name = "Support"
    parent = "community"
    pre = "<i class='fa fa-phone'></i>"
    url  = "/support/"
    weight = 2

[[menu.main]]
    name = "Services"
    parent = "community"
    pre = "<i class='fa fa-wrench'></i>"
    url  = "/services/"
    weight = 3

[[menu.main]]
    identifier = "contribute"
    name = "Contribute"
    parent = "community"
    pre = "<i class='fa fa-github'></i>"
    url  = "/contribute/"
    weight = 4



[[menu.main]]
    name = "News"
    parent = "about"
    pre = "<i class='fa fa-rss'></i>"
    url  = "/blog/"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/openboxes/openboxes"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/openboxes_"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "Blogger"
    url = "https://blog.openboxes.com"
    pre = "<i class='fa fa-2x fa-rss'></i>"


[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:support@openboxes.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/openboxes"
    pre = "<i class='fa fa-2x fa-linkedin'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "OpenBoxes"
    defaultKeywords = ["openboxes"]
    defaultDescription = "Open-source supply chain software"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "support@openboxes.com"

    about_us = "<p>OpenBoxes is an open-source supply chain management system used to manage supplies and medications for healthcare facilities and disaster relief efforts.</p>"
    copyright = "Copyright (c) 2010-2018, OpenBoxes"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p><strong>OpenBoxes</strong>
        <br>Cambridge, MA 02140
        <br>
        <strong>United States</strong>
      </p>
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us at <a href="tel:">+1 (617) 475-0619</a> or 
        <a href="mailto:support@openboxes.com">support@openboxes.com</a>.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.benefits]
    enable = true

[params.features]
    enable = true

[params.tutorials]
    enable = true

[params.services]
    enable = true

[params.support]
    enable = true

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Unfortunately, that's harder said than done."

[params.demo]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Demo"
    subtitle = ""
    link_url = "https://demo.openboxes.com/openboxes/auth/signup"
    link_text = "Signup"

[params.clients]
    enable = true
    title = "Our Supporters"
    subtitle = ""

[params.partners]
    enable = true
    title = "Our Partners"
    subtitle = ""


[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = ""
