# Hugo configuration
baseURL = "https://openboxes.com/"
languageCode = "en-us"
title = "OpenBoxes"
theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "openboxes"

# Enable Google Analytics by entering your tracking code
# googleAnalytics = "UA-37396941-2"
googleAnalytics = "G-4244ZMRC67"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

#[[menu.main]]
#    identifier = "home"
#    name = "Home"
#    pre = "<i class='fa fa-home'></i>"
#    url = "/"
#    weight = 1

# About
[[menu.main]]
    identifier = "about"
    name = "About"
    url  = "/about"
    weight = 10

# Benefits
[[menu.main]]
    name = "Benefits"
    url  = "/#benefits"
    weight = 20

# Features
[[menu.main]]
    name = "Features"
    url  = "/features/"
    weight = 30

# Demo
[[menu.main]]
    identifier = "demo"
    name = "Demo"
    weight = 50

[[menu.main]]
    identifier = "try-demo"
    parent = "demo"
    pre = "<i class='fa fa-desktop'></i>"
    name = "Try our Demo"
    url  = "https://demo.openboxes.com/openboxes/auth/signup"
    post = "<p class='text-large'>Experience OpenBoxes firsthand with our interactive demo.</p> Take a guided tour of our inventory management software and explore its powerful features in action. Get a feel for how OpenBoxes can transform your supply chain operations and streamline your inventory management processes. It's the perfect way to see if OpenBoxes is the right fit for your organization without any commitment."
    weight = 1

[[menu.main]]
    identifier = "schedule-demo"
    name = "Schedule a Demo"
    parent = "demo"
    pre = "<i class='fa fa-calendar-check-o'></i>"
    post = "<p class='text-large'>Ready for a more personalized demonstration?</p> Schedule a one-on-one demo with our experts. During this session, we'll delve into your specific needs and challenges, showcasing how OpenBoxes can address them effectively. Our team will provide insights, answer your questions, and tailor the demo to your industry and use case. Schedule your demo today to discover how OpenBoxes can optimize your supply chain."
    url = "https://calendly.com/openboxes/demo"
    weight = 2

[[menu.main]]
    identifier = "launch-demo"
    name = "Launch your own Demo"
    parent = "demo"
    pre = "<i class='fa fa-server'></i>"
    post = "<p class='text-large'>Want to explore OpenBoxes at your own pace?</p> Launch your own demo server and get hands-on experience with our software. This option allows you to test, configure, and experiment with OpenBoxes in a dedicated environment. It's an ideal choice for those who prefer a self-guided approach to evaluate the capabilities and flexibility of OpenBoxes. Start your demo server now and discover the potential of our inventory management solution."
    url = "https://marketplace.digitalocean.com/apps/openboxes-server?refcode=da4712a483b4"
    weight = 3



# Pricing

[[menu.main]]
    name = "Hosting"
    url  = "/pricing/"
    weight = 40

# Resources

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 60

# Documentation

[[menu.main]]
    identifier = "docs"
    name = "Documentation"
    parent = "resources"
    weight = 50

[[menu.main]]
    name = "About OpenBoxes"
    parent = "docs"
    pre = "<i class='fa fa-cube'></i>"
    url  = "/about"
    weight = 1

[[menu.main]]
    identifier = "user-guide"
    name = "User Guide"
    parent = "docs"
    pre = "<i class='fa fa-user-circle'></i>"
    url  = "https://help.openboxes.com"
    weight = 1

[[menu.main]]
    identifier = "installation-guide"
    name = "Installation Guide"
    parent = "docs"
    pre = "<i class='fa fa-wrench'></i>"
    url  = "https://docs.openboxes.com/en/develop/"
    weight = 2

[[menu.main]]
    name = "Contributing Guide"
    parent = "docs"
    pre = "<i class='fa fa-check-square'></i>"
    url = "https://github.com/openboxes/openboxes/blob/develop/CONTRIBUTING.md"
    weight = 4


[[menu.main]]
    name = "Roadmap"
    parent = "docs"
    pre = "<i class='fa fa-road'></i>"
    url  = "/roadmap/"
    weight = 5

[[menu.main]]
    identifier = "release-notes"
    name = "Release Notes"
    parent = "docs"
    pre = "<i class='fa fa-file-text-o'></i>"
    url  = "https://community.openboxes.com/tag/release-notes"
    weight = 6

[[menu.main]]
    name = "Latest Announcements"
    parent = "docs"
    pre = "<i class='fa fa-newspaper-o'></i>"
    url  = "/blog/"
    weight = 7

[[menu.main]]
    name = "Total Cost of Ownership (TCO)"
    parent = "docs"
    pre = "<i class='fa fa-money'></i>"
    url  = "/cost-analysis"
    weight = 8



# Getting Started

[[menu.main]]
    identifier = "getting-started"
    name = "Getting Started"
    parent = "resources"
    url  = "/getting-started/"
    weight = 60

[[menu.main]]
    identifier = "schedule-discussion"
    name = "Schedule a Discussion"
    parent = "getting-started"
    pre = "<i class='fa fa-phone'></i>"
    url = "https://calendly.com/openboxes/discussion"
    weight = 3

[[menu.main]]
    name = "Follow a Tutorial"
    parent = "getting-started"
    pre = "<i class='fa fa-laptop'></i>"
    url  = "/tutorials/"
    weight = 4

[[menu.main]]
    name = "Watch a YouTube Video"
    parent = "getting-started"
    pre = "<i class='fa fa-youtube-play'></i>"
    url  = "https://www.youtube.com/@openboxes/videos"
    weight = 5

[[menu.main]]
    identifier = "training"
    parent = "getting-started"
    name = "Schedule a Training"
    url  = "https://calendly.com/openboxes/training"
    pre = "<i class='fa fa-calendar'></i>"
    weight = 6

[[menu.main]]
    identifier = "cost-analysis"
    parent = "getting-started"
    pre = "<i class='fa fa-dollar'></i>"
    name = "Schedule a Cost Analysis"
    url  = "https://calendly.com/openboxes/cost-analysis"
    weight = 7

[[menu.main]]
    identifier = "request-quote"
    parent = "getting-started"
    pre = "<i class='fa fa-file-text-o'></i>"
    name = "Request a Quote"
    url  = "/quote"
    weight = 8

[[menu.main]]
    name = "Deploy to Digital Ocean"
    parent = "getting-started"
    pre = "<i class='fa fa-cloud'></i>"
    url = "https://marketplace.digitalocean.com/apps/openboxes-server?refcode=da4712a483b4"
    weight = 9

#[[menu.main]]
#    name = "Deploy to Azure"
#    parent = "getting-started"
#    pre = "<i class='fa fa-cloud'></i>"
#    url = "https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fopenboxes%2Fopenboxes-devops%2Fmaster%2Farm-template%2Fopenboxes-arm.json"
#    weight = 10


[[menu.main]]
    name = "Consulting Services"
    parent = "getting-started"
    pre = "<i class='fa fa-handshake-o'></i>"
    url  = "/pricing/#services"
    weight = 11


# Community

[[menu.main]]
    identifier = "community"
    name = "Community"
    parent = "resources"
    weight = 70

[[menu.main]]
    identifier = "join-community"
    name = "Ask a Question"
    parent = "community"
    pre = "<i class='fa fa-comments-o'></i>"
    url = "https://community.openboxes.com/new-topic?category=general"
    weight = 2

[[menu.main]]
    name = "Report a Bug"
    parent = "community"
    pre = "<i class='fa fa-bug'></i>"
    url = "https://community.openboxes.com/new-topic?category=bugs"
    weight = 3

[[menu.main]]
    name = "Request a Feature"
    parent = "community"
    pre = "<i class='fa fa-key'></i>"
    url = "https://community.openboxes.com/new-topic?category=features"
    weight = 4

[[menu.main]]
    name = "Implementations"
    parent = "community"
    pre = "<i class='fa fa-map'></i>"
    url  = "/users/"
    weight = 5

[[menu.main]]
    name = "Source Code"
    parent = "community"
    pre = "<i class='fa fa-code'></i>"
    post = "<i class='fa fa-external-link'></i>"
    url  = "https://github.com/openboxes/openboxes"
    weight = 6

[[menu.main]]
    identifier = "api-guide"
    name = "REST API Guide"
    parent = "community"
    pre = "<i class='fa fa-link'></i>"
    url  = "https://docs.openboxes.com/en/develop/api-guide"
    weight = 7

[[menu.main]]
    identifier = "openapi-docs"
    name = "OpenAPI Docs"
    parent = "community"
    pre = "<i class='fa fa-terminal'></i>"
    url  = "https://community.openboxes.com/t/swagger-docs-yes-swagger-docs/480"
    post = "<span class='badge bg-secondary'>beta</span>"
    weight = 8

[[menu.main]]
    name = "Database Schema"
    parent = "community"
    pre = "<i class='fa fa-database'></i>"
    url  = "https://dbdocs.io/jmiranda/openboxes"
    weight = 9





# Footer social links menu

[[menu.social]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/openboxes/openboxes"
    pre = "<i class='fa fa-github'></i>"

[[menu.social]]
    weight = 2
    name = "Twitter"
    url = "https://twitter.com/openboxes_"
    pre = "<i class='fa fa-twitter'></i>"

[[menu.social]]
    weight = 4
   name = "Blogger"
    url = "https://openboxes.com/blog"
    pre = "<i class='fa fa-rss-square'></i>"

[[menu.social]]
    weight = 5
    name = "Discourse"
    url = "/community"
    pre = "<i class='fa fa-comment'></i>"

[[menu.social]]
    weight = 3
    name = "YouTube"
    url = "https://openboxes.com/videos"
    pre = "<i class='fa fa-youtube'></i>"


# Top bar social links menu

[[menu.topbar]]
    weight = 2
    name = "Support"
    url = "/community"
    pre = "<i class='fa fa-1x fa-support'></i>"
    post = "<i class='fa fa-external-link'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Community"
#    url = "https://community.openboxes.com"
#    pre = "<i class='fa fa-group'></i>"


#[[menu.topbar]]
#    weight = 2
#    name = "LinkedIn"
#    url = "https://www.linkedin.com/company/openboxes"
#    pre = "<i class='fa fa-2x fa-linkedin'></i>"


# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/openboxes/openboxes"
#    pre = "<i class='fa fa-2x fa-github'></i>"




[params]
    viewMorePostLink = "/blog/"
    author = "OpenBoxes"
    defaultKeywords = ["openboxes"]
    defaultDescription = "Open-source supply chain software"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "support@openboxes.com"

    about_us = "<p>OpenBoxes is an open-source supply chain management system used to manage supplies and medications for healthcare facilities and disaster relief efforts.</p>"
    copyright = "Copyright (c) 2010-2023, OpenBoxes"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Logo
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"

    # Address
    #address = """<p><strong>OpenBoxes</strong>
    #    <br>Shorewood, WI 53211
    #    <br>
    #    <strong>United States</strong>
    #  </p>
    #  """
    #latitude = "-12.043333"
    #longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """
        <a href="mailto:support@openboxes.com" class="btn btn-link-primary"><i class="fa fa-envelope fa-lg"></i> support@openboxes.com</a>
        <a href="tel:+16174750619" class="btn btn-link"><i class="fa fa-phone fa-lg"></i> +1-617-475-0619</a>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.benefits]
    enable = true
    title = "Benefits"

[params.features]
    enable = true

[params.pricingfaqs]
    enable = true

[params.tutorials]
    enable = true

[params.services]
    enable = false

[params.support]
    enable = true

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = ""

[params.demo]
    enable = true
    icon = "fa fa-desktop"
    title = "Demo"
    subtitle = "The moment you've all been waiting for ..."
    link_url = "https://demo.openboxes.com/openboxes/auth/signup"
    link_text = "Try the demo"
    schedule_link_url = "https://calendly.com/openboxes/demo"
    schedule_link_text = "Schedule a Demo"

[params.users]
    enable = true
    title = "Users"
    subtitle = "The following organizations are currently using OpenBoxes for their healthcare supply chain needs."

[params.partners]
    enable = true
    title = "Partners"
    subtitle = "The following organizations provide funding, contributions, project management, implementations services and support to the OpenBoxes community."

[params.supporters]
    enable = true
    title = "Supporters"
    subtitle = "Whether it's a free open-source license or discounted hosting, the following organizations have provided generous support to OpenBoxes over the years."

[params.recent_posts]
    enable = true
    title = "Recent News"
    subtitle = ""

[params.ethicalads]
    enable = true

[params.adsense]
    enable = false

[params.calendly]
    enable = true
    title = "Schedule a Demo"
    url = ""
