# Hugo configuration
baseURL = "https://openboxes.com/"
languageCode = "en-us"
title = "OpenBoxes"
theme = "hugo-universal-theme"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = "openboxes"

# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-37396941-2"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

#[[menu.main]]
#    identifier = "home"
#    name = "Home"
#    pre = "<i class='fa fa-home'></i>"
#    url = "/"
#    weight = 1

# About
[[menu.main]]
    identifier = "about"
    name = "About"
    weight = 10

[[menu.main]]
    name = "Features"
    url  = "/features/"
    weight = 15

[[menu.main]]
    name = "About Us"
    parent = "about"
    url  = "/about"
    weight = 1

[[menu.main]]
    name = "Roadmap"
    parent = "about"
    url  = "/roadmap/"
    weight = 4

[[menu.main]]
    name = "Implementations"
    parent = "about"
    url  = "/users/"
    weight = 5

[[menu.main]]
    name = "News"
    parent = "about"
    url  = "/blog/"
    weight = 1

[[menu.main]]
    name = "Pricing"
    weight = 20

# Demo
[[menu.main]]
    name = "Demo"
    url  = "/demo/"
    weight = 30

# Getting Started
[[menu.main]]
    identifier = "getting-started"
    name = "Get Started"
    url  = "/getting-started/"
    weight = 40

[[menu.main]]
    name = "Documentation"
    parent = "getting-started"
    url  = "http://docs.openboxes.com/en/develop/"
    weight = 1

[[menu.main]]
    name = "Downloads"
    parent = "getting-started"
    url  = "https://github.com/openboxes/openboxes/releases"
    weight = 2

[[menu.main]]
    name = "Source Code"
    parent = "getting-started"
    url  = "https://github.com/openboxes/openboxes"
    weight = 3

[[menu.main]]
    name = "Installation"
    parent = "getting-started"
    url  = "https://openboxes.readthedocs.io/en/develop/installation/"
    weight = 4

[[menu.main]]
    name = "Tutorials"
    parent = "getting-started"
    url  = "/tutorials/"
    weight = 5

# Documentation
#[[menu.main]]
#    name = "Docs"
#    pre = "<i class='fa fa-file'></i>"
#    post = "<i class='fa fa-external-link'></i>"
#    url  = "http://docs.openboxes.com/en/develop/"
#    weight = 4

# Community
[[menu.main]]
    identifier = "community"
    name = "Community"
    url  = "https://discuss.openboxes.com"
    weight = 50



#[[menu.main]]
#    identifier = "discuss"
#    name = "Discuss"
#    parent = "community"
#    pre = "<i class='fa fa-comment'></i>"
#    url  = "http://discuss.openboxes.com"
#    weight = 1

#[[menu.main]]
#    name = "Support"
#    parent = "community"
#    pre = "<i class='fa fa-phone'></i>"
#    url  = "/support/"
#    weight = 2

# Services
#[[menu.main]]
#    name = "Services"
#    pre = "<i class='fa fa-cog'></i>"
#    post = ""
#    url  = "/services/"
#    weight = 60

#[[menu.main]]
#    identifier = "contribute"
#    name = "Contribute"
#    parent = "community"
#    pre = "<i class='fa fa-github'></i>"
#    url  = "/contribute/"
#    weight = 5


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/openboxes/openboxes"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/openboxes_"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "Blogger"
    url = "https://blog.openboxes.com"
    pre = "<i class='fa fa-2x fa-rss'></i>"


[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:support@openboxes.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/openboxes"
    pre = "<i class='fa fa-2x fa-linkedin'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "OpenBoxes"
    defaultKeywords = ["openboxes"]
    defaultDescription = "Open-source supply chain software"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "support@openboxes.com"

    about_us = "<p>OpenBoxes is an open-source supply chain management system used to manage supplies and medications for healthcare facilities and disaster relief efforts.</p>"
    copyright = "Copyright (c) 2010-2019, OpenBoxes"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Logo
    logo = "img/logo-eagle.png"
    logo_small = "img/logo-small.png"

    # Address
    #address = """<p><strong>OpenBoxes</strong>
    #    <br>Cambridge, MA 02140
    #    <br>
    #    <strong>United States</strong>
    #  </p>
    #  """
    #latitude = "-12.043333"
    #longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact sales and support at <a href="tel:+16174750619">+1-617-475-0619</a> or
        <a href="mailto:support@openboxes.com">support@openboxes.com</a>.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+16174750619" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="mailto:support@openboxes.com" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.benefits]
    enable = true

[params.features]
    enable = true

[params.tutorials]
    enable = true

[params.services]
    enable = false

[params.support]
    enable = true

[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = ""

[params.demo]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Demo"
    subtitle = "The moment we've all been waiting for ..."
    link_url = "https://demo.openboxes.com/openboxes/auth/signup"
    link_text = "Signup on our demo"

[params.clients]
    enable = true
    title = "Our Supporters"
    subtitle = ""

[params.partners]
    enable = true
    title = "Our Partners"
    subtitle = ""


[params.recent_posts]
    enable = true
    title = "Recent news"
    subtitle = ""
