---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: data/carousel
  label: Carousel
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/benefits
  label: Benefits
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/clients
  label: Implementations
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/features
  label: Features
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/partners
  label: Partners
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/services
  label: Services
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/support
  label: Support
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/testimonials
  label: Testimonials
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/tutorials
  label: Tutorials
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: data/users
  label: Users
  create: documents
  match: "*.yaml"
  new_doc_ext: yaml
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.49
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.49
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: '0.49'
